// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCo7wZ4PdGCdVWbMBsRtvUj6apI0EwAmU',
    appId: '1:310283961386:web:9e3e5c5b42ff8107cfaf53',
    messagingSenderId: '310283961386',
    projectId: 'app-agni-d27b9',
    authDomain: 'app-agni-d27b9.firebaseapp.com',
    storageBucket: 'app-agni-d27b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Z5WA_-MDLsroKEeU7imtrlpxS00pLLc',
    appId: '1:310283961386:android:15a834755b73c495cfaf53',
    messagingSenderId: '310283961386',
    projectId: 'app-agni-d27b9',
    storageBucket: 'app-agni-d27b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbFCnMQxmdJwf11jnqYm-yGE3XUJjPyNY',
    appId: '1:310283961386:ios:632d91f874bd06fbcfaf53',
    messagingSenderId: '310283961386',
    projectId: 'app-agni-d27b9',
    storageBucket: 'app-agni-d27b9.appspot.com',
    iosClientId: '310283961386-3mt54v5e9e9du2qg4id1fsbdpqf26t1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAgni',
  );
}
